# Generated by Django 3.1.3 on 2020-12-04 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('name', models.CharField(max_length=256, verbose_name='用户名')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('email', models.CharField(max_length=256, unique=True, verbose_name='邮箱')),
                ('phone_number', models.CharField(max_length=256, unique=True, verbose_name='电话')),
                ('role', models.CharField(choices=[('admin', '管理员'), ('user', '用户')], default='用户', max_length=256, verbose_name='角色权限')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('last_login_time', models.DateTimeField(verbose_name='最近登录时间')),
                ('delete', models.BooleanField(default=0, verbose_name='删除')),
            ],
        ),
    ]
