# Generated by Django 3.1.3 on 2020-12-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0003_auto_20201205_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_no',
            field=models.CharField(max_length=128, verbose_name='用户编号'),
        ),
    ]
