# Generated by Django 3.1.3 on 2020-12-05 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0004_auto_20201205_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_no',
        ),
    ]
