# Generated by Django 3.1.3 on 2020-12-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0005_remove_user_user_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_no',
            field=models.CharField(max_length=128, null=True, unique=True, verbose_name='用户编号'),
        ),
    ]
