# Generated by Django 3.1.3 on 2020-12-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0006_user_user_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_no',
            field=models.CharField(max_length=128, null=True, verbose_name='用户编号'),
        ),
    ]
