# Generated by Django 3.1.3 on 2020-12-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0007_auto_20201207_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('user_no', models.CharField(max_length=128, null=True, verbose_name='用户编号')),
            ],
        ),
    ]
