# Generated by Django 3.1.3 on 2020-12-07 13:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0008_currentuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentuser',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='登录时间'),
            preserve_default=False,
        ),
    ]
