# Generated by Django 3.1.3 on 2020-12-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0010_remove_user_user_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentuser',
            name='logout',
            field=models.BooleanField(default=0, verbose_name='删除'),
        ),
    ]
