# Generated by Django 3.1.3 on 2020-12-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0013_auto_20201207_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login_time',
            field=models.DateTimeField(null=True, verbose_name='最近登录时间'),
        ),
    ]
