# Generated by Django 3.1.3 on 2020-12-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0014_auto_20201207_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentuser',
            name='logout',
            field=models.BooleanField(default=1, verbose_name='登出'),
        ),
    ]
