# Generated by Django 3.1.3 on 2020-12-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0015_currentuser_logout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentuser',
            name='logout',
            field=models.BooleanField(default=0, verbose_name='登出'),
        ),
    ]
