# Generated by Django 3.1.3 on 2020-12-07 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0016_auto_20201207_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currentuser',
            options={'ordering': ['-update_time']},
        ),
    ]
