# Generated by Django 3.1.3 on 2020-12-07 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0017_auto_20201207_1716'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-create_time']},
        ),
    ]
