# Generated by Django 3.1.3 on 2020-12-17 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0018_auto_20201207_1717'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrentUser',
        ),
    ]
