# Generated by Django 3.1.3 on 2020-12-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('sensor_id', models.CharField(max_length=128, verbose_name='传感器id')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('station_id', models.CharField(max_length=128, verbose_name='加氢站编号')),
                ('station_name', models.CharField(max_length=128, verbose_name='加氢站名称')),
                ('sort', models.CharField(max_length=128, verbose_name='传感器类别')),
                ('location', models.CharField(max_length=128, verbose_name='所在位置')),
                ('info', models.CharField(blank=True, max_length=128, verbose_name='详细信息')),
                ('status', models.CharField(blank=True, max_length=128, verbose_name='当前状态')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('comment', models.CharField(blank=True, max_length=128, verbose_name='备注')),
                ('delete', models.BooleanField(default=0, verbose_name='删除')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('station_id', models.CharField(max_length=128, unique=True, verbose_name='加氢站编号')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='加氢站名称')),
                ('address', models.CharField(max_length=128, verbose_name='地址')),
                ('status', models.CharField(blank=True, max_length=128, verbose_name='当前状态')),
                ('delete', models.BooleanField(default=0, verbose_name='删除')),
            ],
        ),
    ]
