# Generated by Django 3.1.3 on 2020-12-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sensor_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('sensor_id', models.CharField(max_length=128, verbose_name='传感器id')),
                ('user_no', models.CharField(max_length=128, null=True, verbose_name='用户编号')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('operate', models.IntegerField(max_length=128, verbose_name='操作类型')),
            ],
        ),
    ]
