# Generated by Django 3.1.3 on 2020-12-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sensor_manage', '0002_sensorrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorrecord',
            name='operate',
            field=models.IntegerField(verbose_name='操作类型'),
        ),
    ]
