# Generated by Django 3.1.3 on 2020-12-17 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_sensor_manage', '0003_auto_20201217_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='info',
        ),
    ]
