# Generated by Django 3.1.3 on 2020-12-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sensor_manage', '0004_remove_sensor_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='last_update_time',
            field=models.DateTimeField(null=True, verbose_name='修改时间'),
        ),
    ]
