# Generated by Django 3.1.3 on 2020-12-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sensor_manage', '0005_auto_20201217_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='unit',
            field=models.CharField(blank=True, max_length=128, verbose_name='单位'),
        ),
        migrations.AlterField(
            model_name='sensorrecord',
            name='update_time',
            field=models.DateTimeField(verbose_name='修改时间'),
        ),
    ]
