# Generated by Django 3.1.3 on 2020-12-24 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_sensor_manage', '0006_auto_20201221_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='status',
        ),
    ]
