# Generated by Django 3.1.3 on 2020-11-20 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(max_length=256, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256, unique=True)),
                ('phone_number', models.CharField(max_length=256, unique=True)),
                ('role', models.CharField(choices=[('admin', '管理员'), ('user', '用户')], default='用户', max_length=256)),
                ('create_time', models.DateTimeField()),
                ('last_login_time', models.DateTimeField()),
            ],
        ),
    ]
